Repository TeamDearToday/Deartoday-Server, pull requests merged in 2022-07, with the labels that each got.

#2 Feature/1 initiation
  .eslintrc.js
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierrc.js
  README.md
  package.json
  src/controllers/index.ts
  src/index.ts
  src/interfaces/common/PostBaseResponseDto.ts
  src/loaders/db.ts
  src/modules/checkObjectIdValid.ts
  src/modules/responseMessage.ts
  src/modules/statusCode.ts
  src/modules/util.ts
  src/routes/index.ts
  src/services/index.ts
  tsconfig.json
  yarn.lock
Labels: 🍺정훈🍺

#4 [Feat] add nodemon.json
  nodemon.json
Labels: 🍺정훈🍺, docs

#6 Feature/5 mongodb
  package.json
  src/config/index.ts
  src/index.ts
  src/loaders/db.ts
  yarn.lock
Labels: 🍺정훈🍺, feat

#9 Feature/8 schema
  src/interfaces/message/MessageInfo.ts
  src/interfaces/oldMedia/OldMediaInfo.ts
  src/interfaces/timeTravel/TimeTravelInfo.ts
  src/interfaces/user/UserInfo.ts
  src/loaders/db.ts
  src/models/Message.ts
  src/models/OldMedia.ts
  src/models/TimeTravel.ts
  src/models/User.ts
Labels: 🍺정훈🍺, feat

#13 Feature/12 fix schema
  src/interfaces/user/UserInfo.ts
  src/models/User.ts
Labels: 🍺정훈🍺, fix

#18 [Docs] Readme.md 작성
  README.md
Labels: 🦋루희🦋, docs

#19 Feature/15 login
  package.json
  src/config/index.ts
  src/controllers/auth/AuthController.ts
  src/interfaces/common/JwtPayloadInfo.ts
  src/interfaces/user/UserInfo.ts
  src/interfaces/user/UserLoginDto.ts
  src/middlewares/auth.ts
  src/models/User.ts
  src/modules/exceptionMessage.ts
  src/modules/jwtHandler.ts
  src/modules/responseMessage.ts
  src/services/auth/AuthService.ts
  src/services/auth/external/AppleApi.ts
  src/services/auth/external/KakaoApi.ts
  yarn.lock
Labels: 🍺정훈🍺, fix, feat

#21 [Chore] #11 - change package.json code
  package.json
Labels: 🦋루희🦋, docs

#25 Feature/23 get question
  package.json
  src/controllers/timeTravel/TimeTravelController.ts
  src/interfaces/timeTravel/GetQuestionDto.ts
  src/modules/responseMessage.ts
  src/modules/shuffleQuestion.ts
  src/routes/TimeTravelRouter.ts
  src/services/timetravel/TimeTravelService.ts
  yarn.lock
Labels: 🍺정훈🍺, feat

#28 Feature/26 get time travel all
  src/controllers/timeTravel/TimeTravelController.ts
  src/interfaces/timeTravel/GetTimeTravelAllDto.ts
  src/modules/responseMessage.ts
  src/routes/TimeTravelRouter.ts
  src/services/timetravel/TimeTravelService.ts
Labels: 🍺정훈🍺, feat

#30 Feature/29 logout
  src/controllers/auth/AuthController.ts
  src/controllers/timeTravel/TimeTravelController.ts
  src/interfaces/user/UserLogoutDto.ts
  src/modules/exceptionMessage.ts
  src/modules/responseMessage.ts
  src/routes/AuthRouter.ts
  src/services/auth/AuthService.ts
Labels: 🍺정훈🍺, feat

#33 [Feat] oldMedia GET API
  src/controllers/timeTravel/TimeTravelController.ts
  src/interfaces/oldMedia/OldMediaResponseDto.ts
  src/modules/responseMessage.ts
  src/routes/TimeTravelRouter.ts
  src/services/timetravel/TimeTravelService.ts
Labels: 🍺정훈🍺, feat

#27 [Feat] GetAnswers / GetTimeTravelDetail API 구현
  package-lock.json
  package.json
  src/controllers/timeTravel/TimeTravelController.ts
  src/interfaces/message/MessageInfo.ts
  src/interfaces/timeTravel/GetAnswersDto.ts
  src/interfaces/timeTravel/GetTimeTravelDetailDto.ts
  src/interfaces/timeTravel/TimeTravelCreateDto.ts
  src/models/Message.ts
  src/modules/responseMessage.ts
  src/routes/TimeTravelRouter.ts
  src/services/timetravel/TimeTravelService.ts
  yarn.lock
Labels: 🦋루희🦋, feat

#37 Feature/35 mocha kakao login
  package.json
  src/index.ts
  src/services/timetravel/TimeTravelService.ts
  src/test/auth.spec.ts
  src/test/timeTravel.spec.ts
  tsconfig.json
  yarn.lock
Labels: 🍺정훈🍺, feat

#39 Feature/38 fix login
  src/controllers/auth/AuthController.ts
  src/modules/exceptionMessage.ts
  src/services/auth/AuthService.ts
  src/test/auth.spec.ts
Labels: 🍺정훈🍺, fix

#41 [Add] #40 - add unauthorized error case in kakao login
  src/test/auth.spec.ts
Labels: 🍺정훈🍺, feat

#43 Feature/42 get time travel count test
  src/test/auth.spec.ts
  src/test/timeTravel.spec.ts
Labels: 🍺정훈🍺, feat

#45 Feature/44 logout test
  src/controllers/auth/AuthController.ts
  src/modules/jwtHandler.ts
  src/services/auth/AuthService.ts
  src/test/auth.spec.ts
Labels: 🍺정훈🍺, feat

#48 [Fix] #47 - fix error
  src/services/timetravel/TimeTravelService.ts
Labels: 🍺정훈🍺, fix

#50 [Fix] getTimeTravelDetail _id field 삭제
  src/services/timetravel/TimeTravelService.ts
Labels: 🦋루희🦋, fix

#52 Feature/46 post time travel test
  src/test/image/test.JPG
  src/test/timeTravel.spec.ts
Labels: 🍺정훈🍺, feat

#54 Feature/53 get old media test
  src/services/auth/AuthService.ts
  src/test/timeTravel.spec.ts
Labels: 🍺정훈🍺, feat

#56 Feature/55 old media fix
  src/controllers/timeTravel/TimeTravelController.ts
  src/modules/responseMessage.ts
Labels: 🍺정훈🍺, fix

#58 Feature/57 fix user
  src/services/timetravel/TimeTravelService.ts
Labels: 🍺정훈🍺, fix

#65 [Fix] #64 - fix questions
  src/modules/shuffleQuestion.ts
Labels: 🍺정훈🍺, fix

#67 Feature/66 get time travel list test
  src/test/timeTravel.spec.ts
Labels: 🍺정훈🍺, feat

#69 Feature/68 get time travel detail test
  src/test/timeTravel.spec.ts
Labels: 🍺정훈🍺, feat

#71 Feature/70 time travel 404
  src/services/timetravel/TimeTravelService.ts
Labels: 🍺정훈🍺, fix

#73 [Fix] getAnswers api response body 수정
  src/services/timetravel/TimeTravelService.ts
Labels: 🥳루희🥳, fix

#75 [Fix] postTimeTravel api 예외처리
  .gitignore
  src/controllers/timeTravel/TimeTravelController.ts
  src/services/timetravel/TimeTravelService.ts
Labels: 🥳루희🥳, feat

#78 Feature/34 push alram
  .gitignore
  package.json
  src/controllers/auth/AuthController.ts
  src/services/auth/AuthService.ts
  src/services/auth/PushAlarmService.ts
  src/services/auth/TokenService.ts
  tsconfig.json
  yarn.lock
Labels: 🍺정훈🍺, feat

#80 Feature/79 apple login test
  src/test/auth.spec.ts
Labels: 🍺정훈🍺, feat

#82 Feature/81 husky
  .eslintrc.js
  .husky/pre-commit
  .husky/pre-push
  package.json
  yarn.lock
Labels: 🍺정훈🍺, feat

#84 [Feat] 한국 표준시간대로 맞게 설정
  package-lock.json
  package.json
  src/modules/shuffleQuestion.ts
  yarn.lock
Labels: 🥳루희🥳, fix, feat

#86 Feature/85 fix logout
  src/controllers/auth/AuthController.ts
  src/services/auth/AuthService.ts
Labels: 🍺정훈🍺, fix

#88 Feature/87 fix push
  src/controllers/auth/AuthController.ts
  src/services/auth/AuthService.ts
  src/services/auth/PushAlarmService.ts
  src/services/timetravel/TimeTravelService.ts
Labels: 🍺정훈🍺, fix

#90 [Fix] #89 - fix sort of getTimeTravelList
  src/services/timetravel/TimeTravelService.ts
Labels: 🍺정훈🍺, fix

#93 Feature/91 agenda
  package.json
  src/modules/responseMessage.ts
  src/services/auth/PushAlarmService.ts
  yarn.lock
Labels: 🍺정훈🍺, feat
